spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka:9092
      bindings:
        event-consumer:
          group: example-consumer
          destination: data_stream
          contentType: application/json
        event-producer:
          destination: data_stream
          contentType: application/json