spring:
  cloud:
    stream:
      function:
        definition: domainService
      bindings:
        domainService-in-0:
          destination: active.web-domains
      kafka:
        bindings:
          domainService-in-0:
            consumer:
              configuration:
                value:
                  deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
        binder:
          brokers: my-kafka:9092
        streams:
          binder:
            application-id: service